# Generated by Django 3.0.5 on 2020-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='seguidos',
            field=models.ManyToManyField(blank=True, to='practica.Usuario'),
        ),
    ]
